// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/e1esm/casino-transaction-system/api-gateway/src/internal/entities"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetTransactionByID provides a mock function for the type MockClient
func (_mock *MockClient) GetTransactionByID(ctx context.Context, id uuid.UUID) (entities.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entities.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entities.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetTransactionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByID'
type MockClient_GetTransactionByID_Call struct {
	*mock.Call
}

// GetTransactionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockClient_Expecter) GetTransactionByID(ctx interface{}, id interface{}) *MockClient_GetTransactionByID_Call {
	return &MockClient_GetTransactionByID_Call{Call: _e.mock.On("GetTransactionByID", ctx, id)}
}

func (_c *MockClient_GetTransactionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockClient_GetTransactionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetTransactionByID_Call) Return(transaction entities.Transaction, err error) *MockClient_GetTransactionByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockClient_GetTransactionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (entities.Transaction, error)) *MockClient_GetTransactionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactions provides a mock function for the type MockClient
func (_mock *MockClient) GetTransactions(ctx context.Context, filter entities.TransactionFilter, orderBy string, limit int64, offset int64) ([]entities.Transaction, int, error) {
	ret := _mock.Called(ctx, filter, orderBy, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []entities.Transaction
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TransactionFilter, string, int64, int64) ([]entities.Transaction, int, error)); ok {
		return returnFunc(ctx, filter, orderBy, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TransactionFilter, string, int64, int64) []entities.Transaction); ok {
		r0 = returnFunc(ctx, filter, orderBy, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.TransactionFilter, string, int64, int64) int); ok {
		r1 = returnFunc(ctx, filter, orderBy, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.TransactionFilter, string, int64, int64) error); ok {
		r2 = returnFunc(ctx, filter, orderBy, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_GetTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactions'
type MockClient_GetTransactions_Call struct {
	*mock.Call
}

// GetTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entities.TransactionFilter
//   - orderBy string
//   - limit int64
//   - offset int64
func (_e *MockClient_Expecter) GetTransactions(ctx interface{}, filter interface{}, orderBy interface{}, limit interface{}, offset interface{}) *MockClient_GetTransactions_Call {
	return &MockClient_GetTransactions_Call{Call: _e.mock.On("GetTransactions", ctx, filter, orderBy, limit, offset)}
}

func (_c *MockClient_GetTransactions_Call) Run(run func(ctx context.Context, filter entities.TransactionFilter, orderBy string, limit int64, offset int64)) *MockClient_GetTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.TransactionFilter
		if args[1] != nil {
			arg1 = args[1].(entities.TransactionFilter)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_GetTransactions_Call) Return(transactions []entities.Transaction, n int, err error) *MockClient_GetTransactions_Call {
	_c.Call.Return(transactions, n, err)
	return _c
}

func (_c *MockClient_GetTransactions_Call) RunAndReturn(run func(ctx context.Context, filter entities.TransactionFilter, orderBy string, limit int64, offset int64) ([]entities.Transaction, int, error)) *MockClient_GetTransactions_Call {
	_c.Call.Return(run)
	return _c
}
