// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/e1esm/casino-transaction-system/tx-manager/src/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRepository
func (_mock *MockRepository) Add(ctx context.Context, transactions ...models.Transaction) error {
	var tmpRet mock.Arguments
	if len(transactions) > 0 {
		tmpRet = _mock.Called(ctx, transactions)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...models.Transaction) error); ok {
		r0 = returnFunc(ctx, transactions...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - transactions ...models.Transaction
func (_e *MockRepository_Expecter) Add(ctx interface{}, transactions ...interface{}) *MockRepository_Add_Call {
	return &MockRepository_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx}, transactions...)...)}
}

func (_c *MockRepository_Add_Call) Run(run func(ctx context.Context, transactions ...models.Transaction)) *MockRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Transaction
		var variadicArgs []models.Transaction
		if len(args) > 1 {
			variadicArgs = args[1].([]models.Transaction)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Add_Call) Return(err error) *MockRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Add_Call) RunAndReturn(run func(ctx context.Context, transactions ...models.Transaction) error) *MockRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll(ctx context.Context, filters models.TransactionFilter, orderBy string, limit int64, offset int64) ([]models.Transaction, error) {
	ret := _mock.Called(ctx, filters, orderBy, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TransactionFilter, string, int64, int64) ([]models.Transaction, error)); ok {
		return returnFunc(ctx, filters, orderBy, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TransactionFilter, string, int64, int64) []models.Transaction); ok {
		r0 = returnFunc(ctx, filters, orderBy, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.TransactionFilter, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, filters, orderBy, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.TransactionFilter
//   - orderBy string
//   - limit int64
//   - offset int64
func (_e *MockRepository_Expecter) GetAll(ctx interface{}, filters interface{}, orderBy interface{}, limit interface{}, offset interface{}) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filters, orderBy, limit, offset)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(ctx context.Context, filters models.TransactionFilter, orderBy string, limit int64, offset int64)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.TransactionFilter
		if args[1] != nil {
			arg1 = args[1].(models.TransactionFilter)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(transactions []models.Transaction, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, filters models.TransactionFilter, orderBy string, limit int64, offset int64) ([]models.Transaction, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(transaction *models.Transaction, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Transaction, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
