// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/e1esm/casino-transaction-system/tx-manager/src/internal/broker/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDLQProducer creates a new instance of MockDLQProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQProducer {
	mock := &MockDLQProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDLQProducer is an autogenerated mock type for the DLQProducer type
type MockDLQProducer struct {
	mock.Mock
}

type MockDLQProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQProducer) EXPECT() *MockDLQProducer_Expecter {
	return &MockDLQProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockDLQProducer
func (_mock *MockDLQProducer) Produce(ctx context.Context, entries []types.FailedEntry) {
	_mock.Called(ctx, entries)
	return
}

// MockDLQProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockDLQProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []types.FailedEntry
func (_e *MockDLQProducer_Expecter) Produce(ctx interface{}, entries interface{}) *MockDLQProducer_Produce_Call {
	return &MockDLQProducer_Produce_Call{Call: _e.mock.On("Produce", ctx, entries)}
}

func (_c *MockDLQProducer_Produce_Call) Run(run func(ctx context.Context, entries []types.FailedEntry)) *MockDLQProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.FailedEntry
		if args[1] != nil {
			arg1 = args[1].([]types.FailedEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQProducer_Produce_Call) Return() *MockDLQProducer_Produce_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDLQProducer_Produce_Call) RunAndReturn(run func(ctx context.Context, entries []types.FailedEntry)) *MockDLQProducer_Produce_Call {
	_c.Run(run)
	return _c
}
