// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/e1esm/casino-transaction-system/tx-manager/src/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSaverService creates a new instance of MockSaverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaverService {
	mock := &MockSaverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSaverService is an autogenerated mock type for the SaverService type
type MockSaverService struct {
	mock.Mock
}

type MockSaverService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSaverService) EXPECT() *MockSaverService_Expecter {
	return &MockSaverService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSaverService
func (_mock *MockSaverService) Create(ctx context.Context, transactions ...models.Transaction) error {
	var tmpRet mock.Arguments
	if len(transactions) > 0 {
		tmpRet = _mock.Called(ctx, transactions)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...models.Transaction) error); ok {
		r0 = returnFunc(ctx, transactions...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSaverService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSaverService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transactions ...models.Transaction
func (_e *MockSaverService_Expecter) Create(ctx interface{}, transactions ...interface{}) *MockSaverService_Create_Call {
	return &MockSaverService_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx}, transactions...)...)}
}

func (_c *MockSaverService_Create_Call) Run(run func(ctx context.Context, transactions ...models.Transaction)) *MockSaverService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Transaction
		var variadicArgs []models.Transaction
		if len(args) > 1 {
			variadicArgs = args[1].([]models.Transaction)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSaverService_Create_Call) Return(err error) *MockSaverService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSaverService_Create_Call) RunAndReturn(run func(ctx context.Context, transactions ...models.Transaction) error) *MockSaverService_Create_Call {
	_c.Call.Return(run)
	return _c
}
