// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function for the type MockValidator
func (_mock *MockValidator) Struct(t interface{}) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type MockValidator_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - t interface{}
func (_e *MockValidator_Expecter) Struct(t interface{}) *MockValidator_Struct_Call {
	return &MockValidator_Struct_Call{Call: _e.mock.On("Struct", t)}
}

func (_c *MockValidator_Struct_Call) Run(run func(t interface{})) *MockValidator_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_Struct_Call) Return(err error) *MockValidator_Struct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Struct_Call) RunAndReturn(run func(t interface{}) error) *MockValidator_Struct_Call {
	_c.Call.Return(run)
	return _c
}
