// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/e1esm/casino-transaction-system/api-gateway/src/internal/proto/tx-manager"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockProtoClient creates a new instance of MockProtoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtoClient {
	mock := &MockProtoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtoClient is an autogenerated mock type for the ProtoClient type
type MockProtoClient struct {
	mock.Mock
}

type MockProtoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtoClient) EXPECT() *MockProtoClient_Expecter {
	return &MockProtoClient_Expecter{mock: &_m.Mock}
}

// GetTransactionByFilters provides a mock function for the type MockProtoClient
func (_mock *MockProtoClient) GetTransactionByFilters(ctx context.Context, in *tx_manager.GetTransactionByFiltersRequest, opts ...grpc.CallOption) (*tx_manager.GetTransactionByFiltersResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByFilters")
	}

	var r0 *tx_manager.GetTransactionByFiltersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tx_manager.GetTransactionByFiltersRequest, ...grpc.CallOption) (*tx_manager.GetTransactionByFiltersResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tx_manager.GetTransactionByFiltersRequest, ...grpc.CallOption) *tx_manager.GetTransactionByFiltersResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx_manager.GetTransactionByFiltersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *tx_manager.GetTransactionByFiltersRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProtoClient_GetTransactionByFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByFilters'
type MockProtoClient_GetTransactionByFilters_Call struct {
	*mock.Call
}

// GetTransactionByFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - in *tx_manager.GetTransactionByFiltersRequest
//   - opts ...grpc.CallOption
func (_e *MockProtoClient_Expecter) GetTransactionByFilters(ctx interface{}, in interface{}, opts ...interface{}) *MockProtoClient_GetTransactionByFilters_Call {
	return &MockProtoClient_GetTransactionByFilters_Call{Call: _e.mock.On("GetTransactionByFilters",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProtoClient_GetTransactionByFilters_Call) Run(run func(ctx context.Context, in *tx_manager.GetTransactionByFiltersRequest, opts ...grpc.CallOption)) *MockProtoClient_GetTransactionByFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tx_manager.GetTransactionByFiltersRequest
		if args[1] != nil {
			arg1 = args[1].(*tx_manager.GetTransactionByFiltersRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProtoClient_GetTransactionByFilters_Call) Return(getTransactionByFiltersResponse *tx_manager.GetTransactionByFiltersResponse, err error) *MockProtoClient_GetTransactionByFilters_Call {
	_c.Call.Return(getTransactionByFiltersResponse, err)
	return _c
}

func (_c *MockProtoClient_GetTransactionByFilters_Call) RunAndReturn(run func(ctx context.Context, in *tx_manager.GetTransactionByFiltersRequest, opts ...grpc.CallOption) (*tx_manager.GetTransactionByFiltersResponse, error)) *MockProtoClient_GetTransactionByFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByID provides a mock function for the type MockProtoClient
func (_mock *MockProtoClient) GetTransactionByID(ctx context.Context, in *tx_manager.GetTransactionByIDRequest, opts ...grpc.CallOption) (*tx_manager.GetTransactionByIDResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *tx_manager.GetTransactionByIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tx_manager.GetTransactionByIDRequest, ...grpc.CallOption) (*tx_manager.GetTransactionByIDResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tx_manager.GetTransactionByIDRequest, ...grpc.CallOption) *tx_manager.GetTransactionByIDResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx_manager.GetTransactionByIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *tx_manager.GetTransactionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProtoClient_GetTransactionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByID'
type MockProtoClient_GetTransactionByID_Call struct {
	*mock.Call
}

// GetTransactionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - in *tx_manager.GetTransactionByIDRequest
//   - opts ...grpc.CallOption
func (_e *MockProtoClient_Expecter) GetTransactionByID(ctx interface{}, in interface{}, opts ...interface{}) *MockProtoClient_GetTransactionByID_Call {
	return &MockProtoClient_GetTransactionByID_Call{Call: _e.mock.On("GetTransactionByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProtoClient_GetTransactionByID_Call) Run(run func(ctx context.Context, in *tx_manager.GetTransactionByIDRequest, opts ...grpc.CallOption)) *MockProtoClient_GetTransactionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tx_manager.GetTransactionByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*tx_manager.GetTransactionByIDRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProtoClient_GetTransactionByID_Call) Return(getTransactionByIDResponse *tx_manager.GetTransactionByIDResponse, err error) *MockProtoClient_GetTransactionByID_Call {
	_c.Call.Return(getTransactionByIDResponse, err)
	return _c
}

func (_c *MockProtoClient_GetTransactionByID_Call) RunAndReturn(run func(ctx context.Context, in *tx_manager.GetTransactionByIDRequest, opts ...grpc.CallOption) (*tx_manager.GetTransactionByIDResponse, error)) *MockProtoClient_GetTransactionByID_Call {
	_c.Call.Return(run)
	return _c
}
